/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.Klijent;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author sleza
 */
public class FormaLoginRegistracija extends javax.swing.JFrame {

    /**
     * Creates new form FormaLoginRegistracija
     */
    public FormaLoginRegistracija() {
        initComponents();
        this.setSize(1200, 600);
        centrirajFrejm();
        panelLogin.setVisible(true);
        panelRegistracije.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lblEmailLogin = new javax.swing.JLabel();
        txtEmailLogin = new javax.swing.JTextField();
        lblLoznikaLogin = new javax.swing.JLabel();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnPrijaviSe = new javax.swing.JButton();
        panelRegistracije = new javax.swing.JPanel();
        lblEmailRegistracija = new javax.swing.JLabel();
        lblImeRegistracija = new javax.swing.JLabel();
        lblPrezimeRegistracija = new javax.swing.JLabel();
        lblKorisnickoImeRegistracija = new javax.swing.JLabel();
        lblLozinakRegistracija = new javax.swing.JLabel();
        lblPotvrdaLozinkeRegistracija = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtKorisnickoIme = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtPasswordPotvrda = new javax.swing.JPasswordField();
        btnRegistrujSe = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnRegistration = new javax.swing.JButton();
        panelLevi = new javax.swing.JPanel();
        panelDesni = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in / Sing in");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1000, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        panelLogin.setBackground(new java.awt.Color(34, 40, 44));
        panelLogin.setLayout(null);

        lblEmailLogin.setBackground(new java.awt.Color(102, 102, 102));
        lblEmailLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailLogin.setText("Email:");
        panelLogin.add(lblEmailLogin);
        lblEmailLogin.setBounds(30, 30, 140, 30);

        txtEmailLogin.setBackground(new java.awt.Color(102, 102, 102));
        txtEmailLogin.setForeground(new java.awt.Color(255, 255, 255));
        panelLogin.add(txtEmailLogin);
        txtEmailLogin.setBounds(190, 30, 220, 30);

        lblLoznikaLogin.setBackground(new java.awt.Color(102, 102, 102));
        lblLoznikaLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLoznikaLogin.setText("Lozinka:");
        panelLogin.add(lblLoznikaLogin);
        lblLoznikaLogin.setBounds(30, 70, 140, 30);

        txtPasswordLogin.setBackground(new java.awt.Color(102, 102, 102));
        txtPasswordLogin.setForeground(new java.awt.Color(255, 255, 255));
        panelLogin.add(txtPasswordLogin);
        txtPasswordLogin.setBounds(190, 70, 220, 30);

        btnPrijaviSe.setBackground(new java.awt.Color(102, 102, 102));
        btnPrijaviSe.setForeground(new java.awt.Color(255, 255, 255));
        btnPrijaviSe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/icons8_user_32px_1.png"))); // NOI18N
        btnPrijaviSe.setText("Log in");
        btnPrijaviSe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrijaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijaviSeActionPerformed(evt);
            }
        });
        panelLogin.add(btnPrijaviSe);
        btnPrijaviSe.setBounds(190, 110, 218, 30);

        getContentPane().add(panelLogin);
        panelLogin.setBounds(270, 90, 420, 160);

        panelRegistracije.setBackground(new java.awt.Color(34, 40, 44));
        panelRegistracije.setLayout(null);

        lblEmailRegistracija.setBackground(new java.awt.Color(102, 102, 102));
        lblEmailRegistracija.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailRegistracija.setText("Email:");
        panelRegistracije.add(lblEmailRegistracija);
        lblEmailRegistracija.setBounds(30, 30, 140, 30);

        lblImeRegistracija.setBackground(new java.awt.Color(102, 102, 102));
        lblImeRegistracija.setForeground(new java.awt.Color(255, 255, 255));
        lblImeRegistracija.setText("Ime:");
        panelRegistracije.add(lblImeRegistracija);
        lblImeRegistracija.setBounds(30, 70, 140, 30);

        lblPrezimeRegistracija.setBackground(new java.awt.Color(102, 102, 102));
        lblPrezimeRegistracija.setForeground(new java.awt.Color(255, 255, 255));
        lblPrezimeRegistracija.setText("Prezime:");
        panelRegistracije.add(lblPrezimeRegistracija);
        lblPrezimeRegistracija.setBounds(30, 110, 140, 30);

        lblKorisnickoImeRegistracija.setBackground(new java.awt.Color(102, 102, 102));
        lblKorisnickoImeRegistracija.setForeground(new java.awt.Color(255, 255, 255));
        lblKorisnickoImeRegistracija.setText("Korisnicko ime:");
        panelRegistracije.add(lblKorisnickoImeRegistracija);
        lblKorisnickoImeRegistracija.setBounds(30, 150, 140, 30);

        lblLozinakRegistracija.setBackground(new java.awt.Color(102, 102, 102));
        lblLozinakRegistracija.setForeground(new java.awt.Color(255, 255, 255));
        lblLozinakRegistracija.setText("Lozinka:");
        panelRegistracije.add(lblLozinakRegistracija);
        lblLozinakRegistracija.setBounds(30, 190, 140, 30);

        lblPotvrdaLozinkeRegistracija.setBackground(new java.awt.Color(102, 102, 102));
        lblPotvrdaLozinkeRegistracija.setForeground(new java.awt.Color(255, 255, 255));
        lblPotvrdaLozinkeRegistracija.setText("Potvrda loznike:");
        panelRegistracije.add(lblPotvrdaLozinkeRegistracija);
        lblPotvrdaLozinkeRegistracija.setBounds(30, 230, 140, 30);

        txtEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistracije.add(txtEmail);
        txtEmail.setBounds(190, 30, 220, 30);

        txtIme.setBackground(new java.awt.Color(102, 102, 102));
        txtIme.setForeground(new java.awt.Color(255, 255, 255));
        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });
        panelRegistracije.add(txtIme);
        txtIme.setBounds(190, 70, 220, 30);

        txtPrezime.setBackground(new java.awt.Color(102, 102, 102));
        txtPrezime.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistracije.add(txtPrezime);
        txtPrezime.setBounds(190, 110, 218, 30);

        txtKorisnickoIme.setBackground(new java.awt.Color(102, 102, 102));
        txtKorisnickoIme.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistracije.add(txtKorisnickoIme);
        txtKorisnickoIme.setBounds(190, 150, 218, 30);

        txtPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistracije.add(txtPassword);
        txtPassword.setBounds(190, 190, 218, 30);

        txtPasswordPotvrda.setBackground(new java.awt.Color(102, 102, 102));
        txtPasswordPotvrda.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistracije.add(txtPasswordPotvrda);
        txtPasswordPotvrda.setBounds(190, 230, 218, 30);

        btnRegistrujSe.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistrujSe.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrujSe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/icons8_add_user_male_32px.png"))); // NOI18N
        btnRegistrujSe.setText("Registruj se");
        btnRegistrujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrujSeActionPerformed(evt);
            }
        });
        panelRegistracije.add(btnRegistrujSe);
        btnRegistrujSe.setBounds(190, 270, 218, 48);

        getContentPane().add(panelRegistracije);
        panelRegistracije.setBounds(270, 90, 420, 350);

        btnLogin.setBackground(new java.awt.Color(102, 102, 102));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/icons8_user_male_30px.png"))); // NOI18N
        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(420, 10, 130, 60);

        btnRegistration.setBackground(new java.awt.Color(102, 102, 102));
        btnRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/icons8_add_user_male_30px.png"))); // NOI18N
        btnRegistration.setText("Sing in");
        btnRegistration.setToolTipText("");
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistration);
        btnRegistration.setBounds(540, 10, 150, 60);

        panelLevi.setBackground(new java.awt.Color(21, 25, 28));
        getContentPane().add(panelLevi);
        panelLevi.setBounds(0, 0, 1200, 600);

        panelDesni.setBackground(new java.awt.Color(34, 40, 44));
        getContentPane().add(panelDesni);
        panelDesni.setBounds(500, 0, 700, 600);
        panelDesni.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrijaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijaviSeActionPerformed
        String email = txtEmailLogin.getText();
        String lozinka = new String(txtPasswordLogin.getPassword());
        Klijent k = new Klijent(-1, "korisnickoIme", lozinka, "ime", "prezime", email);
        //mozda ne bih treba da smaram server sa upitom o tome da li je sve popunio al nema veze stoji i na serverskoj strani
        if (email.isEmpty() || lozinka.isEmpty()) {
            return;
        }
        Klijent klijent;
        try {
            klijent = kontroler.Kontroler.getInstance().UlogujSe(k);
            JOptionPane.showMessageDialog(this, "Korisnik: " + klijent.getIme() + " " + klijent.getPrezime() + ".\nUspesno ste se prijavili!");
            prikaziGlavnuFormu(klijent);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }//GEN-LAST:event_btnPrijaviSeActionPerformed

    private void btnRegistrujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrujSeActionPerformed
        char[] niz = txtPassword.getPassword();
        String lozinka = String.copyValueOf(niz);
        char[] niz2 = txtPasswordPotvrda.getPassword();
        String lozinka2 = String.copyValueOf(niz2);
        if (!lozinka.equals(lozinka2)) {
            JOptionPane.showMessageDialog(this, "Potvrda lozinke neuspesna");
            txtPassword.setText("");
            txtPasswordPotvrda.setText("");
            return;
        }
        String korisnickoIme = txtKorisnickoIme.getText();
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String email = txtEmail.getText();
        //mozda ne bih treba da smaram server sa upitom o tome da li je sve popunio al nema veze stoji i na serverskoj strani
        if (korisnickoIme.isEmpty() || lozinka.isEmpty() || ime.isEmpty() || prezime.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
            return;
        }

        Klijent klijent = new Klijent(-1, korisnickoIme, lozinka, ime, prezime, email);
        try {
            Kontroler.getInstance().RegistrujSe(klijent);
            btnLoginActionPerformed(evt);
            txtIme.setText("");
            txtPrezime.setText("");
            txtEmail.setText("");
            txtKorisnickoIme.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            txtEmail.setText("");
        }
    }//GEN-LAST:event_btnRegistrujSeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        panelLogin.setVisible(true);
        panelRegistracije.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        panelLogin.setVisible(false);
        panelRegistracije.setVisible(true);
    }//GEN-LAST:event_btnRegistrationActionPerformed

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dracula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaLoginRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaLoginRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaLoginRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaLoginRegistracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaLoginRegistracija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPrijaviSe;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JButton btnRegistrujSe;
    private javax.swing.JLabel lblEmailLogin;
    private javax.swing.JLabel lblEmailRegistracija;
    private javax.swing.JLabel lblImeRegistracija;
    private javax.swing.JLabel lblKorisnickoImeRegistracija;
    private javax.swing.JLabel lblLozinakRegistracija;
    private javax.swing.JLabel lblLoznikaLogin;
    private javax.swing.JLabel lblPotvrdaLozinkeRegistracija;
    private javax.swing.JLabel lblPrezimeRegistracija;
    private javax.swing.JPanel panelDesni;
    private javax.swing.JPanel panelLevi;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegistracije;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JPasswordField txtPasswordPotvrda;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void centrirajFrejm() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    private void prikaziGlavnuFormu(Klijent klijent) {
        FormaRezervacije fr = new FormaRezervacije();
        fr.setK(klijent);
        fr.setVisible(true);
        this.setVisible(false);
    }
}
