/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import domen.Klijent;
import domen.MedjuStanica;
import domen.Polazak;
import domen.Rezervacija;
import domen.Stanica;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import kontroler.Kontroler;
import modeli.ModelTabelePolasci;
import modeli.ModelTabeleRezervacija;
import sat.Sat;

/**
 *
 * @author sleza
 */
public class FormaRezervacije extends javax.swing.JFrame {

    private Klijent k;
    Sat s = new Sat();
    SimpleDateFormat smf = new SimpleDateFormat("dd.MM.yyyy");
    ModelTabelePolasci mtp = new ModelTabelePolasci();
    ModelTabeleRezervacija mtr = new ModelTabeleRezervacija();
    ArrayList<Rezervacija> listaRezervacija = new ArrayList<>();
    ArrayList<MedjuStanica> listaMedjustanica = new ArrayList<>();
    public static int BROJ_PRIKAZA = 0;
    public static int DUGME = 0;

    /**
     * Creates new form FormaRezervacije
     */
    public FormaRezervacije() {
        initComponents();
        this.setSize(1560, 564);
        centrirajFrame();
        postaviVelicinuPanela(1560, 570);
        panelMojeRezervacije.setVisible(false);
        panelKlijenta.setVisible(false);
        srediDaneMeseceGodinu();
        ulepsajTabelu(tablePolasci);
        ulepsajTabelu(tabelMojeRezeravacije);
        srediTabelu();
        ucitajStanice();
        ucitajMedjustanice();
        pretraziZaDatumPolaske(new Date());

        s.sat(lblSat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRezervacija = new javax.swing.JButton();
        btnKlijent = new javax.swing.JButton();
        btnMojeRezervacije = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblSat = new javax.swing.JLabel();
        btnOdjaviSe = new javax.swing.JButton();
        panelRezervacije = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPocetnaStanica = new javax.swing.JComboBox();
        cmbKrajnjaStanica = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnPretraziPolaske = new javax.swing.JButton();
        cmbGodina = new javax.swing.JComboBox();
        cmbMeseci = new javax.swing.JComboBox();
        cmbDani = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePolasci = new javax.swing.JTable();
        lblNazivTabele = new javax.swing.JLabel();
        btnRezervisi = new javax.swing.JButton();
        cmbViseOPolasku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSviPolasciDUGME = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRefreshTabela = new javax.swing.JButton();
        panelMojeRezervacije = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMojeRezeravacije = new javax.swing.JTable();
        lblNazivTabeleMojeRezervacije = new javax.swing.JLabel();
        cmbAktivneRezervacije = new javax.swing.JButton();
        btnRealizovaneRezervacije = new javax.swing.JButton();
        btnOtkaziRezervaciju = new javax.swing.JButton();
        panelKlijenta = new javax.swing.JPanel();
        lblEmailRegistracija = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblImeRegistracija = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        lblPrezimeRegistracija = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        lblKorisnickoImeRegistracija = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        lblLozinakRegistracija = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPotvrdaLozinkeRegistracija = new javax.swing.JLabel();
        txtPasswordPotvrda = new javax.swing.JPasswordField();
        btnPromeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnRezervacija.setText("Rezervacija");
        btnRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezervacijaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRezervacija);
        btnRezervacija.setBounds(0, 0, 140, 40);

        btnKlijent.setText("Nalog");
        btnKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlijentActionPerformed(evt);
            }
        });
        getContentPane().add(btnKlijent);
        btnKlijent.setBounds(130, 0, 160, 40);

        btnMojeRezervacije.setText("Moje rezervacije");
        btnMojeRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMojeRezervacijeActionPerformed(evt);
            }
        });
        getContentPane().add(btnMojeRezervacije);
        btnMojeRezervacije.setBounds(280, 0, 160, 40);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 40, 1540, 20);

        lblSat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblSat);
        lblSat.setBounds(921, 0, 440, 40);

        btnOdjaviSe.setText("Odjavi se");
        btnOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviSeActionPerformed(evt);
            }
        });
        getContentPane().add(btnOdjaviSe);
        btnOdjaviSe.setBounds(1380, 0, 160, 40);

        panelRezervacije.setLayout(null);

        jLabel3.setText("DO:");
        panelRezervacije.add(jLabel3);
        jLabel3.setBounds(40, 210, 30, 20);

        jLabel4.setText("OD:");
        panelRezervacije.add(jLabel4);
        jLabel4.setBounds(40, 150, 30, 20);
        panelRezervacije.add(cmbPocetnaStanica);
        cmbPocetnaStanica.setBounds(80, 150, 300, 26);

        cmbKrajnjaStanica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbKrajnjaStanica.setSelectedIndex(-1);
        cmbKrajnjaStanica.setToolTipText("");
        panelRezervacije.add(cmbKrajnjaStanica);
        cmbKrajnjaStanica.setBounds(80, 210, 300, 26);

        jLabel5.setText("DATUM:");
        panelRezervacije.add(jLabel5);
        jLabel5.setBounds(10, 250, 50, 20);

        btnPretraziPolaske.setText("PRETRAZI POLASKE");
        btnPretraziPolaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziPolaskeActionPerformed(evt);
            }
        });
        panelRezervacije.add(btnPretraziPolaske);
        btnPretraziPolaske.setBounds(10, 290, 370, 32);

        cmbGodina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGodina.setSelectedIndex(-1);
        cmbGodina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGodinaItemStateChanged(evt);
            }
        });
        panelRezervacije.add(cmbGodina);
        cmbGodina.setBounds(300, 250, 80, 26);

        cmbMeseci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januar", "Februar", "Mart", "April", "Maj", "Jun", "Jul", "Avgust", "Septembar", "Oktobar", "Novembar", "Decembar" }));
        cmbMeseci.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMeseciItemStateChanged(evt);
            }
        });
        panelRezervacije.add(cmbMeseci);
        cmbMeseci.setBounds(170, 250, 120, 26);

        cmbDani.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDani.setSelectedIndex(-1);
        panelRezervacije.add(cmbDani);
        cmbDani.setBounds(80, 250, 80, 26);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablePolasci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePolasci.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablePolasci.setShowVerticalLines(false);
        tablePolasci.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablePolasci);

        panelRezervacije.add(jScrollPane2);
        jScrollPane2.setBounds(400, 130, 1140, 280);

        lblNazivTabele.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        panelRezervacije.add(lblNazivTabele);
        lblNazivTabele.setBounds(100, 40, 1130, 40);

        btnRezervisi.setText("REZERVISI POLAZAK");
        btnRezervisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezervisiActionPerformed(evt);
            }
        });
        panelRezervacije.add(btnRezervisi);
        btnRezervisi.setBounds(400, 420, 1140, 32);

        cmbViseOPolasku.setText("?");
        cmbViseOPolasku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViseOPolaskuActionPerformed(evt);
            }
        });
        panelRezervacije.add(cmbViseOPolasku);
        cmbViseOPolasku.setBounds(1490, 80, 50, 32);

        jLabel1.setText("Vise o polasku");
        panelRezervacije.add(jLabel1);
        jLabel1.setBounds(1400, 80, 90, 30);

        btnSviPolasciDUGME.setText("SVI DANASNJI POLASCI");
        btnSviPolasciDUGME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSviPolasciDUGMEActionPerformed(evt);
            }
        });
        panelRezervacije.add(btnSviPolasciDUGME);
        btnSviPolasciDUGME.setBounds(1220, 80, 170, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Pretraga:");
        panelRezervacije.add(jLabel2);
        jLabel2.setBounds(10, 40, 90, 40);

        btnRefreshTabela.setText("Osvezi tabelu");
        btnRefreshTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTabelaActionPerformed(evt);
            }
        });
        panelRezervacije.add(btnRefreshTabela);
        btnRefreshTabela.setBounds(1090, 80, 120, 32);

        getContentPane().add(panelRezervacije);
        panelRezervacije.setBounds(0, 0, 1550, 680);

        panelMojeRezervacije.setMinimumSize(new java.awt.Dimension(1250, 570));
        panelMojeRezervacije.setPreferredSize(new java.awt.Dimension(1250, 570));
        panelMojeRezervacije.setRequestFocusEnabled(false);
        panelMojeRezervacije.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tabelMojeRezeravacije.setForeground(new java.awt.Color(0, 0, 0));
        tabelMojeRezeravacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMojeRezeravacije.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelMojeRezeravacije.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelMojeRezeravacije.setShowVerticalLines(false);
        tabelMojeRezeravacije.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelMojeRezeravacije);

        panelMojeRezervacije.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 1510, 220);

        lblNazivTabeleMojeRezervacije.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNazivTabeleMojeRezervacije.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNazivTabeleMojeRezervacije.setText("Tabela rezervacija:");
        panelMojeRezervacije.add(lblNazivTabeleMojeRezervacije);
        lblNazivTabeleMojeRezervacije.setBounds(20, 110, 1190, 40);

        cmbAktivneRezervacije.setText("Aktivne rezervacije");
        cmbAktivneRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAktivneRezervacijeActionPerformed(evt);
            }
        });
        panelMojeRezervacije.add(cmbAktivneRezervacije);
        cmbAktivneRezervacije.setBounds(1150, 60, 210, 32);

        btnRealizovaneRezervacije.setText("Realizovane rezervacije");
        btnRealizovaneRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizovaneRezervacijeActionPerformed(evt);
            }
        });
        panelMojeRezervacije.add(btnRealizovaneRezervacije);
        btnRealizovaneRezervacije.setBounds(1330, 60, 210, 32);

        btnOtkaziRezervaciju.setText("Oktazi rezervaciju");
        btnOtkaziRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziRezervacijuActionPerformed(evt);
            }
        });
        panelMojeRezervacije.add(btnOtkaziRezervaciju);
        btnOtkaziRezervaciju.setBounds(1230, 390, 310, 32);

        getContentPane().add(panelMojeRezervacije);
        panelMojeRezervacije.setBounds(0, 0, 1550, 680);

        panelKlijenta.setLayout(null);

        lblEmailRegistracija.setText("Email:");
        panelKlijenta.add(lblEmailRegistracija);
        lblEmailRegistracija.setBounds(130, 100, 140, 30);
        panelKlijenta.add(txtEmail);
        txtEmail.setBounds(280, 100, 218, 30);

        lblImeRegistracija.setText("Ime:");
        panelKlijenta.add(lblImeRegistracija);
        lblImeRegistracija.setBounds(130, 140, 140, 30);
        panelKlijenta.add(txtIme);
        txtIme.setBounds(280, 140, 218, 30);

        lblPrezimeRegistracija.setText("Prezime:");
        panelKlijenta.add(lblPrezimeRegistracija);
        lblPrezimeRegistracija.setBounds(130, 180, 140, 30);
        panelKlijenta.add(txtPrezime);
        txtPrezime.setBounds(280, 180, 218, 30);

        lblKorisnickoImeRegistracija.setText("Korisnicko ime:");
        panelKlijenta.add(lblKorisnickoImeRegistracija);
        lblKorisnickoImeRegistracija.setBounds(130, 220, 140, 30);
        panelKlijenta.add(txtKorisnickoIme);
        txtKorisnickoIme.setBounds(280, 220, 218, 30);

        lblLozinakRegistracija.setText("Lozinka:");
        panelKlijenta.add(lblLozinakRegistracija);
        lblLozinakRegistracija.setBounds(130, 260, 140, 30);
        panelKlijenta.add(txtPassword);
        txtPassword.setBounds(280, 260, 218, 30);

        lblPotvrdaLozinkeRegistracija.setText("Potvrda loznike:");
        panelKlijenta.add(lblPotvrdaLozinkeRegistracija);
        lblPotvrdaLozinkeRegistracija.setBounds(130, 300, 140, 30);
        panelKlijenta.add(txtPasswordPotvrda);
        txtPasswordPotvrda.setBounds(280, 300, 218, 30);

        btnPromeni.setText("Promeni");
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });
        panelKlijenta.add(btnPromeni);
        btnPromeni.setBounds(280, 342, 218, 32);

        getContentPane().add(panelKlijenta);
        panelKlijenta.setBounds(0, 0, 1550, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziPolaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziPolaskeActionPerformed
        DUGME = 1;
        pretraziPolaskeZaDatum();
    }//GEN-LAST:event_btnPretraziPolaskeActionPerformed

    private void cmbGodinaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGodinaItemStateChanged
        int godina = (int) cmbGodina.getSelectedItem();
        postaviZaPrestupnuGodinu(godina);

    }//GEN-LAST:event_cmbGodinaItemStateChanged

    private void cmbMeseciItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMeseciItemStateChanged
        int index = cmbMeseci.getSelectedIndex();
        int godina = (int) cmbGodina.getSelectedItem();
        postaviDaneZaOdgovarajuciMesec(index);
        postaviZaPrestupnuGodinu(godina);

    }//GEN-LAST:event_cmbMeseciItemStateChanged

    private void btnRezervisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezervisiActionPerformed
        int red = tablePolasci.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Morate obeleziti polazak u tabeli za koji zelite da rezervisete kartu!");
            return;
        }
        Polazak p = mtp.vratiListu().get(red);
//        if (p.getNapomena() != null && (p.getNapomena().contains("OTKAZANO") || p.getNapomena().contains("Otkazano") || p.getNapomena().contains("Otkazan"))) {
//            JOptionPane.showMessageDialog(this, "Polazak je otkazan. Ne mozete ga rezervisati!");
//            return;
//        }
        //ovo moze u validaciji
//        if (p.getDatumPolaska().before(new Date())) {
//            JOptionPane.showMessageDialog(this, "Ne mozete rezervisati kartu za polazak koji je vec realizovan!");
//            return;
//        }
//        Rezervacija rez = new Rezervacija(null, p, null);
//        boolean popunjeno = mtp.popunjeno(rez);
//        if (!popunjeno) {
//            pretraziPolaskeZaDatum();
//        } else {
//            JOptionPane.showMessageDialog(this, "Popunjena su sva mesta!");
//        }
        Date d = new Date();
        Rezervacija r = new Rezervacija(k, p, d);
        try {
            Kontroler.getInstance().rezervisiPolazak(r);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }//GEN-LAST:event_btnRezervisiActionPerformed

    private void btnMojeRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMojeRezervacijeActionPerformed
        panelKlijenta.setVisible(false);
        panelRezervacije.setVisible(false);
        panelMojeRezervacije.setVisible(true);
        ucitajMojeRezervacije();
    }//GEN-LAST:event_btnMojeRezervacijeActionPerformed

    private void btnRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezervacijaActionPerformed
        panelKlijenta.setVisible(false);
        panelMojeRezervacije.setVisible(false);
        panelRezervacije.setVisible(true);
    }//GEN-LAST:event_btnRezervacijaActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String email = txtEmail.getText();
        String korisnickoIme = txtKorisnickoIme.getText();
        char[] niz = txtPassword.getPassword();
        String lozinka = String.copyValueOf(niz);
        char[] niz2 = txtPasswordPotvrda.getPassword();
        String lozinka2 = String.copyValueOf(niz2);
        if (k.getKorisnickoIme().equals(korisnickoIme) && lozinka.isEmpty() && lozinka2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nema promena");
            return;
        }
        if (lozinka.isEmpty() && lozinka2.isEmpty()) {
            lozinka = k.getLozinka();
            lozinka2 = k.getLozinka();
        }
        if (!lozinka.equals(lozinka2)) {
            JOptionPane.showMessageDialog(this, "Niste dobro potvrdili lozinku!");
            return;
        }
        Klijent klijent = new Klijent(k.getKlijentID(), korisnickoIme, lozinka, ime, prezime, email);
        try {
            Kontroler.getInstance().IzmeniNalog(klijent);
            k = klijent;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            return;
        } finally {
            txtPassword.setText("");
            txtPasswordPotvrda.setText("");
        }
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlijentActionPerformed
        panelKlijenta.setVisible(true);
        panelMojeRezervacije.setVisible(false);
        panelRezervacije.setVisible(false);
        txtEmail.setText(k.getEmail());
        txtIme.setText(k.getIme());
        txtPrezime.setText(k.getPrezime());
        txtKorisnickoIme.setText(k.getKorisnickoIme());
        txtEmail.setEnabled(false);
        txtIme.setEnabled(false);
        txtPrezime.setEnabled(false);
    }//GEN-LAST:event_btnKlijentActionPerformed

    private void cmbAktivneRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAktivneRezervacijeActionPerformed
        Date datum = new Date();
        ArrayList<Rezervacija> listaAkt = new ArrayList<>();
        for (Rezervacija rezervacija : listaRezervacija) {
            if (datum.before(rezervacija.getPolazak().getDatumPolaska())) {
                listaAkt.add(rezervacija);
            }
        }
        if (!listaAkt.isEmpty()) {
            mtr.ocistiTabelu();
            mtr.setList(listaAkt);
        } else {
            mtr.ocistiTabelu();
        }
    }//GEN-LAST:event_cmbAktivneRezervacijeActionPerformed

    private void btnRealizovaneRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizovaneRezervacijeActionPerformed
        Date datum = new Date();
        ArrayList<Rezervacija> listaRealizovanih = new ArrayList<>();
        for (Rezervacija rezervacija : listaRezervacija) {
            if (datum.after(rezervacija.getPolazak().getDatumPolaska())) {
                listaRealizovanih.add(rezervacija);
            }
        }
        if (!listaRealizovanih.isEmpty()) {
            mtr.ocistiTabelu();
            mtr.setList(listaRealizovanih);
        } else {
            mtr.ocistiTabelu();
        }

    }//GEN-LAST:event_btnRealizovaneRezervacijeActionPerformed

    private void btnOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviSeActionPerformed
        this.setVisible(false);
        FormaLoginRegistracija flr = new FormaLoginRegistracija();
        flr.setVisible(true);
    }//GEN-LAST:event_btnOdjaviSeActionPerformed

    private void btnOtkaziRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziRezervacijuActionPerformed
        int broj = tabelMojeRezeravacije.getSelectedRow();
        if (broj == -1) {
            JOptionPane.showMessageDialog(this, "Morate da obelezite polazak za koji zelite da otkazete rezervaciju!");
            return;
        }
        Rezervacija r = mtr.getList().get(broj);
        Date danasnji = new Date();

        //Ovo bi trebalo da ide u validaciju
        if (danasnji.after(r.getPolazak().getDatumPolaska())) {
            JOptionPane.showMessageDialog(this, "Polazak je vec realizovan!", "NEUSPESNO OTKAZIVANJE KARTE!", 1);
            return;
        }
        try {
            Kontroler.getInstance().otkaziRezervaciju(r);
            JOptionPane.showMessageDialog(this, "Uspesno ste otkazali rezervaciju!");
            mtr.izbrisiIzTabele(broj);
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOtkaziRezervacijuActionPerformed

    private void cmbViseOPolaskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViseOPolaskuActionPerformed
        int broj = tablePolasci.getSelectedRow();
        if (broj == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite polazak za koji zelite da vidite sve medjustanice!");
            return;
        }
        Polazak p = mtp.getList().get(broj);
        MedjuStanica m = new MedjuStanica(null, p.getLinija(), 0);
        ArrayList<MedjuStanica> listaMedjustanica;
        try {
            listaMedjustanica = Kontroler.getInstance().vratiMiMedjustaniceLiniju(m);
            JOptionPane.showMessageDialog(this, ispisiListu(listaMedjustanica), "LISTA MEDJUSTANICA", 1);
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbViseOPolaskuActionPerformed

    private void btnSviPolasciDUGMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSviPolasciDUGMEActionPerformed
        DUGME = 0;
        try {
            pretraziZaDatumPolaske(new Date());
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSviPolasciDUGMEActionPerformed

    private void btnRefreshTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTabelaActionPerformed
        if (DUGME == 0) {
            pretraziZaDatumPolaske(new Date());
        } else {
            pretraziPolaskeZaDatum();
        }
    }//GEN-LAST:event_btnRefreshTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaRezervacije.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaRezervacije.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaRezervacije.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaRezervacije.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaRezervacije().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKlijent;
    private javax.swing.JButton btnMojeRezervacije;
    private javax.swing.JButton btnOdjaviSe;
    private javax.swing.JButton btnOtkaziRezervaciju;
    private javax.swing.JButton btnPretraziPolaske;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JButton btnRealizovaneRezervacije;
    private javax.swing.JButton btnRefreshTabela;
    private javax.swing.JButton btnRezervacija;
    private javax.swing.JButton btnRezervisi;
    private javax.swing.JButton btnSviPolasciDUGME;
    private javax.swing.JButton cmbAktivneRezervacije;
    private javax.swing.JComboBox cmbDani;
    private javax.swing.JComboBox cmbGodina;
    private javax.swing.JComboBox cmbKrajnjaStanica;
    private javax.swing.JComboBox cmbMeseci;
    private javax.swing.JComboBox cmbPocetnaStanica;
    private javax.swing.JButton cmbViseOPolasku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmailRegistracija;
    private javax.swing.JLabel lblImeRegistracija;
    private javax.swing.JLabel lblKorisnickoImeRegistracija;
    private javax.swing.JLabel lblLozinakRegistracija;
    private javax.swing.JLabel lblNazivTabele;
    private javax.swing.JLabel lblNazivTabeleMojeRezervacije;
    private javax.swing.JLabel lblPotvrdaLozinkeRegistracija;
    private javax.swing.JLabel lblPrezimeRegistracija;
    private javax.swing.JLabel lblSat;
    private javax.swing.JPanel panelKlijenta;
    private javax.swing.JPanel panelMojeRezervacije;
    private javax.swing.JPanel panelRezervacije;
    private javax.swing.JTable tabelMojeRezeravacije;
    private javax.swing.JTable tablePolasci;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordPotvrda;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    public Klijent getK() {
        return k;
    }

    public void setK(Klijent k) {
        this.k = k;
    }

    private void centrirajFrame() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    private void srediDaneMeseceGodinu() {
        cmbDani.removeAllItems();
        cmbGodina.removeAllItems();
        GregorianCalendar gc = new GregorianCalendar();
        int godina = gc.get(Calendar.YEAR);
        int mesec = gc.get(Calendar.MONTH);
        int dan = gc.get(Calendar.DAY_OF_MONTH);
        for (int i = godina; i < godina + 10; i++) {
            cmbGodina.addItem(i);
        }
        postaviDaneZaOdgovarajuciMesec(dan);
        postaviZaPrestupnuGodinu(godina);
        postaviDaneZaOdgovarajuciMesec(mesec);
        cmbGodina.setSelectedItem(godina);
        cmbMeseci.setSelectedIndex(mesec);
        cmbDani.setSelectedItem(dan);

    }

    private void postaviDaneZaOdgovarajuciMesec(int index) {
        if (index == 0 || index == 2 || index == 4 || index == 6 || index == 7 || index == 9 || index == 11) {
            cmbDani.removeAllItems();
            for (int i = 1; i <= 31; i++) {
                cmbDani.addItem(i);
            }
        }
        if (index == 3 || index == 5 || index == 8 || index == 10) {
            cmbDani.removeAllItems();
            for (int i = 1; i <= 30; i++) {
                cmbDani.addItem(i);
            }
        }
    }

    private void postaviZaPrestupnuGodinu(int godina) {
        if (cmbMeseci.getSelectedIndex() == 1) {
            if (godina % 4 == 0) {
                cmbDani.removeAllItems();
                for (int i = 1; i <= 29; i++) {
                    cmbDani.addItem(i);
                }
            } else {
                cmbDani.removeAllItems();
                for (int i = 1; i <= 28; i++) {
                    cmbDani.addItem(i);
                }
            }
        }
    }

    private void ucitajStanice() {
        cmbPocetnaStanica.removeAllItems();
        cmbKrajnjaStanica.removeAllItems();

        ArrayList<Stanica> listaStanica = new ArrayList<>();
        try {
            listaStanica = Kontroler.getInstance().vratiMiSveStanice();
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Stanica stanica : listaStanica) {
            cmbPocetnaStanica.addItem(stanica);
            cmbKrajnjaStanica.addItem(stanica);
        }

    }

    private void srediTabelu() {
        tablePolasci.setModel(mtp);
    }

    //ovde je nesto pobrljavio
    public void postaviVelicinuPanela(int x, int y) {
        panelKlijenta.setSize(x, y);
        panelMojeRezervacije.setSize(x, y);
        panelRezervacije.setSize(x, y);
    }

    public ArrayList<Rezervacija> getListaRezervacija() {
        return listaRezervacija;
    }

    public void setListaRezervacija(ArrayList<Rezervacija> listaRezervacija) {
        this.listaRezervacija = listaRezervacija;
    }

    private void ucitajMedjustanice() {
        listaMedjustanica = new ArrayList<>();
        try {
            listaMedjustanica = Kontroler.getInstance().vratiMiSveMedjustanica();
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean pocentaJeMedjustanica(Polazak polazak, Stanica pocetna, Stanica krajnja) {
        boolean postoji = false;
        if (polazak.getLinija().getStanicaKrajnja().equals(krajnja)) {
            for (MedjuStanica medjuStanica : listaMedjustanica) {
                if (medjuStanica.getStanica().equals(pocetna) && polazak.getLinija().getLinijaID() == medjuStanica.getLinija().getLinijaID()) {
                    return true;
                }
            }
        }
        return postoji;
    }

    private boolean krajnjaJeMedjustnica(Polazak polazak, Stanica krajnja, Stanica pocetna) {
        boolean postoji = false;
        if (polazak.getLinija().getStanicaPocetna().equals(pocetna)) {
            for (MedjuStanica medjuStanica : listaMedjustanica) {
                if (medjuStanica.getStanica().equals(krajnja) && polazak.getLinija().getLinijaID() == medjuStanica.getLinija().getLinijaID()) {
                    return true;
                }
            }
        }
        return postoji;
    }

    //vraca true ako se pocetna i krajnja u okviru nekog polaska a nisu ni prva ni poslednja i ako je prva pre druge
    private boolean pocetnaIKrajnjaSuMedjustanice(Polazak polazak, Stanica krajnja, Stanica pocetna) {
        boolean postojiP = false;
        boolean postojiK = false;
        MedjuStanica m1 = new MedjuStanica();
        MedjuStanica m2 = new MedjuStanica();
        for (MedjuStanica medjuStanica : listaMedjustanica) {
            if (medjuStanica.getStanica().equals(pocetna) && polazak.getLinija().getLinijaID() == medjuStanica.getLinija().getLinijaID()) {
                postojiP = true;
                m1 = medjuStanica;
                break;
            }
        }
        for (MedjuStanica medjuStanica : listaMedjustanica) {
            if (medjuStanica.getStanica().equals(krajnja) && polazak.getLinija().getLinijaID() == medjuStanica.getLinija().getLinijaID()) {
                postojiK = true;
                m2 = medjuStanica;
                break;
            }
        }
        boolean broj = false;
        if (m1.getRedniBroj() < m2.getRedniBroj()) {
            broj = true;
        }

        return postojiK && postojiP && broj;
    }

    private String ispisiListu(ArrayList<MedjuStanica> lista) {
        String listaString = "";
        for (MedjuStanica medjuStanica : lista) {
            listaString += medjuStanica.getRedniBroj() + ". ";
            listaString += medjuStanica.getStanica().getNaziv();
            listaString += "\n";
        }
        return listaString;
    }

    public void pretraziPolaskeZaDatum() {
        DUGME = 1;
        //u kalendaru meseci idu od 0 a u util datu idu od 1
        int godina = (int) cmbGodina.getSelectedItem();
        int mesec = cmbMeseci.getSelectedIndex() + 1;
        int dan = (int) cmbDani.getSelectedItem();
        Stanica pocetna = (Stanica) cmbPocetnaStanica.getSelectedItem();
        Stanica krajnja = (Stanica) cmbKrajnjaStanica.getSelectedItem();
        String datum = dan + "." + mesec + "." + godina;
        Date date = null;
        try {
            date = smf.parse(datum);
        } catch (ParseException ex) {
            Logger.getLogger(FormaRezervacije.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        Polazak p = new Polazak(-1, "", date, null, null, null);

        ArrayList<Polazak> listPolazaka = new ArrayList<>();
        try {
            listPolazaka = Kontroler.getInstance().vratiMiPolaskeZaDatum(p);
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<Polazak> listaZaTabelu = new ArrayList<>();

        for (Polazak polazak : listPolazaka) {
            boolean pocentaJeMedjustanica = pocentaJeMedjustanica(polazak, pocetna, krajnja);
            boolean krajnjaJeMedjustniica = krajnjaJeMedjustnica(polazak, krajnja, pocetna);
            boolean pocetnaIKrajnjaSuMedjustanice = pocetnaIKrajnjaSuMedjustanice(polazak, krajnja, pocetna);
            if ((((polazak.getLinija().getStanicaPocetna().equals(pocetna) || pocentaJeMedjustanica) && (polazak.getLinija().getStanicaKrajnja().equals(krajnja) || krajnjaJeMedjustniica)) || pocetnaIKrajnjaSuMedjustanice)) {
                listaZaTabelu.add(polazak);
            }
        }
        mtp.ocistiTabelu();
        if (listaZaTabelu.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nema polazaka na relaciji " + pocetna.getNaziv() + " - " + krajnja.getNaziv() + " za datum: " + datum);
            lblNazivTabele.setText("Nema polazaka na relaciji " + pocetna.getNaziv() + " - " + krajnja.getNaziv() + " za datum: " + datum);
            return;
        } else {
            lblNazivTabele.setText("Lista polazaka za datum: " + datum + " na liniji: " + pocetna.getNaziv() + " - " + krajnja.getNaziv());
        }
        mtp.setList(listaZaTabelu);
        tablePolasci.setModel(mtp);
    }

    private void pretraziZaDatumPolaske(Date date) {
        Polazak p = new Polazak(-1, "", date, null, null, null);
        ArrayList<Polazak> listPolazaka = new ArrayList<>();
        try {
            listPolazaka = Kontroler.getInstance().vratiMiPolaskeZaDatum(p);
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (listPolazaka.isEmpty()) {
            lblNazivTabele.setText("Nema polazaka za datum: " + smf.format(date));
            return;
        } else {
            lblNazivTabele.setText("Svi polasci za datum: " + smf.format(date));
        }
        mtp.ocistiTabelu();
        mtp.setList(listPolazaka);
        tablePolasci.setModel(mtp);
    }

    public void ulepsajTabelu(JTable tabela) {
        tabela.setRowHeight(25);
        tabela.setFocusable(false);
        tabela.setShowVerticalLines(false);
        tabela.setSelectionBackground(Color.LIGHT_GRAY);
        tabela.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabela.getTableHeader().setOpaque(false);
        tabela.getTableHeader().setBackground(new Color(32, 136, 203));
        tabela.getTableHeader().setForeground(new Color(255, 255, 255));
        tabela.setRowHeight(25);
    }

    private void ucitajMojeRezervacije() {
        ArrayList<Rezervacija> listaRezervacija = new ArrayList<>();
        try {
            listaRezervacija = Kontroler.getInstance().vratiMojeRezervacije(new Rezervacija(k, null, null));
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (BROJ_PRIKAZA == 0) {
            if (listaRezervacija.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vasa lista rezervacija je prazna!");
            }
            BROJ_PRIKAZA++;
        }
        this.setListaRezervacija(listaRezervacija);
        mtr.setList(listaRezervacija);
        tabelMojeRezeravacije.setModel(mtr);
    }
}
